#!/usr/bin/env python3
"""
ผู้ช่วย Obsidian Graph Tool — รักษา graph ของ vault ให้เชื่อมโยงกันเสมอ
วิธีใช้:
    python3 context/admin/obsidian_graph.py audit        # รายงาน orphan / broken links
    python3 context/admin/obsidian_graph.py sync         # regen context/memory/ mirror จาก memory จริง
    python3 context/admin/obsidian_graph.py fix-orphans  # เติม ## Connections ให้ไฟล์ที่โดดเดี่ยว
    python3 context/admin/obsidian_graph.py heal-links   # สร้าง stub ให้ wikilink ที่ยังชี้ไปที่ว่าง
    python3 context/admin/obsidian_graph.py all          # sync -> heal-links -> fix-orphans -> audit

ราก cause ที่กันไว้:
  1) memory อยู่นอก vault (~/.claude/...) -> sync สร้าง mirror stub ใน context/memory/ ให้ [[slug]] resolve
  2) ไฟล์ใหม่ไม่มี Connections -> fix-orphans เติมให้ + กฎใน CLAUDE.md ให้ ผู้ช่วย ทำเองตอนสร้างไฟล์
"""
import os, re, sys, collections

# VAULT = โฟลเดอร์ project นี้ (ที่มี CLAUDE.md) — ดีฟอลต์เดาจากตำแหน่งไฟล์ (context/admin/ -> ราก), override ได้ด้วย env AGIS_VAULT
VAULT = os.environ.get("AGIS_VAULT") or os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# MEM_DIR = ที่เก็บ memory จริงของ Claude Code (นอก vault) — ดีฟอลต์ตาม convention ~/.claude/projects/<vault-path-แทน / ด้วย ->/memory, override ด้วย env AGIS_MEM_DIR
MEM_DIR = os.environ.get("AGIS_MEM_DIR") or os.path.expanduser("~/.claude/projects/" + VAULT.replace("/", "-") + "/memory")
STUB_REL = "context/memory"
HUB_SLUG = "_memory_moc"
IGNORE_DIRS = {".git", ".obsidian", ".continue", "node_modules", ".venv", "__pycache__", ".pytest_cache"}
# path (relative to VAULT) ที่เป็น config ไม่ใช่ vault content — ไม่นับเข้ากราฟ (agent files = auto-gen จาก teams/*/lead.md)
IGNORE_REL_PREFIXES = (".claude/agents" + os.sep,)

# wikilink ที่เป็นตัวอย่าง/placeholder ในเอกสาร ไม่นับเป็น broken จริง
PLACEHOLDER = {
    "wikilink", "link", "card slug อื่น", "MISSION.md", "MISSION",
    "their-name", "name", "slug", "note-name", "การ์ด", "แท็ก",
}

CONN_START = "<!-- agis:connections:start -->"
CONN_END = "<!-- agis:connections:end -->"
STUB_MARK = "<!-- agis:memory-mirror (auto-generated by obsidian_graph.py sync — แก้ที่ memory ต้นทาง) -->"

WIKILINK = re.compile(r"\[\[([^\]|#]+)(?:[#|][^\]]*)?\]\]")
MDLINK = re.compile(r"\[[^\]]*\]\(([^)]+)\)")

# ---------- โหลดไฟล์ vault ----------
def load_vault():
    md_files = []
    for root, dirs, files in os.walk(VAULT):
        dirs[:] = [d for d in dirs if d not in IGNORE_DIRS]
        for f in files:
            if f.endswith(".md"):
                md_files.append(os.path.join(root, f))
    by_base = collections.defaultdict(list)
    by_rel = {}
    for p in md_files:
        rel = os.path.relpath(p, VAULT)
        if rel.startswith(IGNORE_REL_PREFIXES):
            continue
        base = os.path.splitext(os.path.basename(p))[0]
        by_base[base].append(rel)
        by_rel[rel] = p
    return by_rel, by_base

def resolve(target, from_rel, by_rel, by_base):
    target = target.strip().split("#")[0].strip()
    if not target:
        return from_rel
    cand_md = target if target.endswith(".md") else target + ".md"
    from_dir = os.path.dirname(from_rel)
    for c in (cand_md, target):
        joined = os.path.normpath(os.path.join(from_dir, c))
        if joined in by_rel:
            return joined
        if c in by_rel:
            return c
    base = os.path.splitext(os.path.basename(target))[0]
    if base in by_base:
        return by_base[base][0]
    return None

def build_graph(by_rel, by_base):
    out_links = collections.defaultdict(set)
    in_links = collections.defaultdict(set)
    broken = collections.defaultdict(list)
    for rel, path in by_rel.items():
        try:
            text = open(path, encoding="utf-8", errors="ignore").read()
        except Exception:
            continue
        targets = [m.group(1) for m in WIKILINK.finditer(text)]
        for m in MDLINK.finditer(text):
            t = m.group(1)
            if t.startswith(("http", "mailto:", "#")):
                continue
            if not (t.endswith(".md") or "/" in t):
                continue
            targets.append(t)
        for t in targets:
            if t.strip() in PLACEHOLDER or "*" in t or "{{" in t:  # '*'/'{{ }}' = pattern/placeholder ในเอกสาร ไม่ใช่ลิงก์จริง
                continue
            dest = resolve(t, rel, by_rel, by_base)
            if dest and dest != rel:
                out_links[rel].add(dest)
                in_links[dest].add(rel)
            elif dest is None:
                broken[rel].append(t)
    return out_links, in_links, broken

def classify(by_rel, out_links, in_links):
    orphans, in_only, out_only, connected = [], [], [], []
    for rel in by_rel:
        has_out = bool(out_links.get(rel))
        has_in = bool(in_links.get(rel))
        if not has_out and not has_in:
            orphans.append(rel)
        elif has_in and not has_out:
            in_only.append(rel)
        elif has_out and not has_in:
            out_only.append(rel)
        else:
            connected.append(rel)
    return orphans, in_only, out_only, connected

# ---------- parse memory ----------
def parse_memory_desc(path):
    """คืน (description) จาก frontmatter ของไฟล์ memory."""
    try:
        text = open(path, encoding="utf-8", errors="ignore").read()
    except Exception:
        return ""
    m = re.search(r"^---\s*\n(.*?)\n---", text, re.S)
    if not m:
        return ""
    fm = m.group(1)
    dm = re.search(r"^description:\s*(.*(?:\n[ \t]+.*)*)", fm, re.M)
    if not dm:
        return ""
    desc = dm.group(1)
    desc = re.sub(r"\s*\n[ \t]+", " ", desc).strip().strip('"')
    return desc

def memory_slugs():
    out = {}
    for f in sorted(os.listdir(MEM_DIR)):
        if f.endswith(".md") and f != "MEMORY.md":
            out[f[:-3]] = os.path.join(MEM_DIR, f)
    return out

# slug -> ไฟล์จริงใน vault (สำหรับ forward link ให้ stub เชื่อมสองทาง)
# เติมเองเมื่ออยากให้ memory stub ลิงก์ไป project/skill ที่เกี่ยวโดยตรง เช่น
#   "project_myapp": "projects/myapp/spec.md",
FORWARD = {}

def relmd(from_rel, to_rel):
    """สร้าง markdown link path จาก from_rel ไป to_rel."""
    rp = os.path.relpath(to_rel, os.path.dirname(from_rel))
    return rp.replace(os.sep, "/")

# ---------- sync ----------
def cmd_sync():
    stub_dir = os.path.join(VAULT, STUB_REL)
    os.makedirs(stub_dir, exist_ok=True)
    slugs = memory_slugs()
    made = 0
    for slug, mpath in slugs.items():
        desc = parse_memory_desc(mpath) or f"(memory: {slug})"
        stub_rel = f"{STUB_REL}/{slug}.md"
        lines = [
            "---",
            f"name: {slug}",
            "type: memory-mirror",
            f"source: {os.path.join(MEM_DIR, slug + '.md')}",
            "---",
            "",
            STUB_MARK,
            "",
            f"# {slug}",
            "",
            desc,
            "",
            "## Connections",
            f"- [[{HUB_SLUG}]]",
        ]
        fwd = FORWARD.get(slug)
        if fwd and os.path.exists(os.path.join(VAULT, fwd)):
            lines.append(f"- [{os.path.basename(os.path.dirname(fwd)) or fwd}]({relmd(stub_rel, fwd)})")
        lines.append(f"- [ผู้ช่วย CLAUDE.md]({relmd(stub_rel, 'CLAUDE.md')})")
        open(os.path.join(VAULT, stub_rel), "w", encoding="utf-8").write("\n".join(lines) + "\n")
        made += 1
    # hub
    hub_rel = f"{STUB_REL}/{HUB_SLUG}.md"
    hub = [
        "---", f"name: {HUB_SLUG}", "type: moc", "---", "",
        STUB_MARK, "", "# Memory — Map of Content", "",
        "Mirror ของ memory ทั้งหมด (~/.claude) เพื่อให้ Obsidian graph เชื่อมถึงได้.",
        "regen: `python3 context/admin/obsidian_graph.py sync`", "",
    ]
    groups = collections.OrderedDict([
        ("User & Profile", "user_"), ("Feedback / กฎการทำงาน", "feedback_"),
        ("Projects", "project_"), ("Skills", "skill_"),
        ("Reference", "reference_"), ("Workflow", "workflow_"),
    ])
    used = set()
    for title, prefix in groups.items():
        items = sorted(s for s in slugs if s.startswith(prefix))
        if not items:
            continue
        hub.append(f"## {title}")
        for s in items:
            hub.append(f"- [[{s}]]")
            used.add(s)
        hub.append("")
    others = sorted(set(slugs) - used)
    if others:
        hub.append("## อื่นๆ")
        for s in others:
            hub.append(f"- [[{s}]]")
        hub.append("")
    hub += ["## Connections", f"- [wiki index]({relmd(hub_rel, 'context/wiki/_index.md')})",
            f"- [ผู้ช่วย CLAUDE.md]({relmd(hub_rel, 'CLAUDE.md')})"]
    open(os.path.join(VAULT, hub_rel), "w", encoding="utf-8").write("\n".join(hub) + "\n")
    print(f"[sync] สร้าง/รีเฟรช memory stub {made} ไฟล์ + hub ({HUB_SLUG}) ที่ {STUB_REL}/")

# ---------- fix-orphans ----------
def guess_slug(rel):
    # generic: projects/<name>/... -> project_<name> ; .claude/skills/<name>/... -> skill_<name>
    parts = rel.lower().lstrip("./").split("/")
    if len(parts) >= 2 and parts[0] == "projects":
        return "project_" + parts[1].replace("-", "_")
    if len(parts) >= 3 and parts[0] == ".claude" and parts[1] == "skills":
        return "skill_" + parts[2].replace("-", "_")
    return None

def cmd_fix_orphans():
    by_rel, by_base = load_vault()
    out_links, in_links, broken = build_graph(by_rel, by_base)
    orphans, in_only, out_only, connected = classify(by_rel, out_links, in_links)
    fixed = 0
    for rel in sorted(orphans):
        if rel.startswith(STUB_REL):
            continue
        path = by_rel[rel]
        text = open(path, encoding="utf-8", errors="ignore").read()
        if CONN_START in text or "## Connections" in text:
            continue
        links = []
        slug = guess_slug(rel)
        if slug:
            links.append(f"- [[{slug}]]")
        links.append(f"- [ผู้ช่วย CLAUDE.md]({relmd(rel, 'CLAUDE.md')})")
        links.append(f"- [agis.md]({relmd(rel, 'agis.md')})")
        block = f"\n\n{CONN_START}\n## Connections\n" + "\n".join(links) + f"\n{CONN_END}\n"
        if not text.endswith("\n"):
            block = "\n" + block
        open(path, "a", encoding="utf-8").write(block)
        fixed += 1
    print(f"[fix-orphans] เติม ## Connections ให้ {fixed} ไฟล์")

# ---------- heal-links ----------
def cmd_heal_links():
    by_rel, by_base = load_vault()
    out_links, in_links, broken = build_graph(by_rel, by_base)
    targets = set()
    for rel, ts in broken.items():
        for t in ts:
            t = t.strip().split("#")[0].strip()
            if not t or t in PLACEHOLDER or "/" in t or t.endswith(".md"):
                continue
            targets.add(t)
    stub_dir = os.path.join(VAULT, STUB_REL)
    os.makedirs(stub_dir, exist_ok=True)
    made = 0
    for t in sorted(targets):
        # ข้ามถ้ามีไฟล์ชื่อนี้อยู่แล้ว
        if t in by_base:
            continue
        safe = re.sub(r"[^\w\-.]", "_", t)
        dest = os.path.join(stub_dir, safe + ".md")
        if os.path.exists(dest):
            continue
        stub_rel = f"{STUB_REL}/{safe}.md"
        body = [
            "---", f"name: {t}", "type: alias-stub", "---", "",
            STUB_MARK, "", f"# {t}", "",
            f"Stub สำหรับ wikilink `[[{t}]]` ที่ยังไม่มีปลายทางจริง — เชื่อม graph ไว้ก่อน.",
            "", "## Connections", f"- [[{HUB_SLUG}]]",
            f"- [ผู้ช่วย CLAUDE.md]({relmd(stub_rel, 'CLAUDE.md')})",
        ]
        open(dest, "w", encoding="utf-8").write("\n".join(body) + "\n")
        made += 1
    print(f"[heal-links] สร้าง alias stub {made} ไฟล์ (จาก {len(targets)} target)")

# ---------- audit ----------
def cmd_audit():
    by_rel, by_base = load_vault()
    out_links, in_links, broken = build_graph(by_rel, by_base)
    orphans, in_only, out_only, connected = classify(by_rel, out_links, in_links)
    tot_broken = sum(len(v) for v in broken.values())
    print(f"ไฟล์ .md (เนื้อหาจริง): {len(by_rel)}")
    print(f"  เชื่อมสองทาง : {len(connected)}")
    print(f"  in-only      : {len(in_only)}")
    print(f"  out-only     : {len(out_only)}")
    print(f"  ORPHAN       : {len(orphans)}")
    print(f"  broken links : {tot_broken} จุด ({len(broken)} ไฟล์)")
    if orphans:
        print("\nORPHANS:")
        for r in sorted(orphans):
            print("  ", r)
    if tot_broken:
        print("\nBROKEN (ไม่รวม placeholder):")
        for r in sorted(broken):
            print(f"   {r}: " + ", ".join(sorted(set(broken[r]))))

def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else "audit"
    if cmd == "audit":
        cmd_audit()
    elif cmd == "sync":
        cmd_sync()
    elif cmd == "fix-orphans":
        cmd_fix_orphans()
    elif cmd == "heal-links":
        cmd_heal_links()
    elif cmd == "all":
        cmd_sync(); cmd_heal_links(); cmd_fix_orphans()
        print("\n===== AUDIT หลังแก้ =====")
        cmd_audit()
    else:
        print(__doc__)

if __name__ == "__main__":
    main()
